# Generated by Django 5.0.4 on 2024-05-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_options_review_auther_and_more'),
        ('users', '0004_profile_location_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='auther',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
